name = "Kawaii"
license = "MIT"
licenselink = "https://github.com/DTStormBoBo/DTStormBoBo.github.io/blob/master/LICENSE"
description = "A modern and cool Hugo theme with beautiful kawaii aesthetics, dark mode support, and delightful animations"
homepage = "https://github.com/DTStormBoBo/DTStormBoBo.github.io"
demosite = "https://hugo-kawaii.pages.dev/"
tags = ["blog", "minimal", "dark"]
features = ["responsive", "blog", "portfolio", "modern", "animations", "customizable", "fast"]
min_version = "0.147.0"

[author]
  name = "yuis-ice"
  homepage = "https://github.com/yuis-ice"